version: '3.7'
services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8399
    links:
      - mongo
    restart: on-failure

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:27017"]
      interval: 30s
      timeout: 10s
      retries: 5